### ISSUE TITLE
Don't Know How Much Vote Take Back!

### ISSUE THREAD

**Issue by levyashin1** [semuxproject/semux#686] opened 2018-03-03 10:10 UTC
Hi there, i want to take my vote fully but it doesn't show me how many votes i locked with certain.

For example:

![2018-03-03_13-04-35](https://user-images.githubusercontent.com/33433070/36933044-cb5dcfc0-1ee3-11e8-8a1b-d53833982013.png)

It says 245 votes locked, and when i try to take 245 it doesn't allow me. And because i'm voting multiple i can't get it from anywhere. I'm writing a random number like 244,35 and it is there. Now I'm leaving some of my sems locked on that delegator. It should show the amount exactly.

**Comment by witoldsz** [comment] 2018-03-03 10:26
This is because you do not have 245, but 244.319 votes instead. Check this out:

![image](https://user-images.githubusercontent.com/544581/36933211-787cc134-1ed5-11e8-91ec-6a5f577e446d.png)

The GUI rounds the amount in an inconsistent way.

**Comment by levyashin1** [comment] 2018-03-03 11:37
I know this but i voted and upvoted too much and i can't see the definite result even in the explorer. Gui shouldn't round it. Or at least it should give an option to show full stats.

**Comment by orogvany** [comment] 2018-03-03 22:48
dupe of #569

**Comment by cryptokat** [comment] 2018-03-06 11:36
closed by #681

**Closed by cryptokat** 2018-03-06 11:36 UTC
