### ISSUE TITLE
GUI not start cause NullPointer exception

### ISSUE THREAD

**Issue by r1d1-btct** [semuxproject/semux#103] opened 2017-10-21 06:20 UTC
About 1 from 10-20 (or even less often) starts of the wallet I get NullPointer error in logs and GUI not started.

```
10/21 13:04:52 [main] INFO Config - Semux v1.0.0-beta.4
10/21 13:04:52 [main] INFO Config - System booting up: network = 0, coinbase = e0151bc0ab22cfa559c8c5cd7f10d36f97e7a052
10/21 13:04:53 [main] INFO Config - Latest block number = 51009
10/21 13:04:53 [main] INFO NodeManager - Node manager started
10/21 13:04:53 [cons] INFO SemuxBFT - Consensus started
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.semux.gui.panel.HomePanel.refresh(HomePanel.java:218)
        at org.semux.gui.panel.HomePanel.<init>(HomePanel.java:143)
        at org.semux.gui.MainFrame.<init>(MainFrame.java:70)
        at org.semux.GUI.lambda$showMain$0(GUI.java:134)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
10/21 13:04:53 [p2p] INFO PeerServer - Starting peer server: address = 0.0.0.0:5161
10/21 13:04:53 [cons] INFO SemuxBFT - Entered new_height: height = 51010, # validators = 67
10/21 13:04:55 [cons] INFO SemuxBFT - Entered propose: height = 51010, view = 0, primary = false, # connected validators = 1 + 3
10/21 13:05:03 [cons] INFO SemuxBFT - Entered validate: proposal = false, votes = [0, 0] [0, 0] [0, 0]
10/21 13:05:06 [cons] INFO SemuxBFT - Entered propose: height = 51010, view = 1, primary = false, # connected validators = 1 + 5
...
```

The exception is thrown in the second line: 
```
        Block block = model.getLatestBlock();
        this.blockNum.setText(Long.toString(block.getNumber()));
```

I think it's cause sometimes gui-thread EventQueue.invokeLater run GUI before
data-refresh thread run onBlockAdded(kernel.getBlockchain().getLatestBlock()) and as result 
model.getLatestBlock() return null.

**Comment by semuxproject** [comment] 2017-10-22 03:15
Hi r1d1, were you able to re-open the wallet after the above exception?

I just double checked. The data refresh thread starts only after the kernel is started (there the latest block is loaded).

The NullPointerException of getBlockNumber() is usually caused by `database` corruption.

**Comment by r1d1-btct** [comment] 2017-10-22 03:31
As far as I remember, yes. I closed the process and ran it again without problems.
I'll try to repeat this error until I cann't.

**Comment by semuxproject** [comment] 2017-10-22 03:34
If that's the case, this issue should be fixed by last commit :)

**Closed** 2017-10-22 05:07 UTC
Labels: bug
