### ISSUE TITLE
hard restart database corrupt

### ISSUE THREAD

**Issue by borderline23** [semuxproject/semux#194] opened 2017-11-08 08:36 UTC
when computer freeze or need hard restart the database will corrupt so wallet found only invalid block.
the solution is a automatic backup every hour. so if the wallet find invalid block could restore database from backup.

**Comment by orogvany** [comment] 2018-05-18 06:01
can prob close as dupe of #798

**Comment by orogvany** [comment] 2018-05-20 18:08
Duplicates #798

**Closed by orogvany** 2018-05-20 18:08 UTC
