### ISSUE TITLE
Delegates improvement proposal

### ISSUE THREAD

**Issue by lodyman93** [semuxproject/semux#792] opened 2018-04-13 00:34 UTC
How about changing the delegate registration from costing one time fee of 1000 SEMs to number of SEMs to be burned monthly like it's being rented not purchased ..
imo this will make SEMUX more decentralized and the fee can be changed over time  as the reward getting lowered .. 

Or we can use different approach and giving the delegates the ability to transfer the delegation state to other addresses and rename it

All opinions are welcomed

**Comment by orogvany** [comment] 2018-04-21 02:15
There are a few other requests around leasing delegate to another.

IMO, allowing it to be rented introduces other issues.  I guess I'm not sure of other similar alts that allow this type of functionality.  I think that having a large offset of cost to register maintains an even playing field.  If it were just a low monthly fee, it would allow an attacker to enter easier for purposes of abuse.  Renting would give the same attack vector.. a low cost path to abuse.

**Comment by orogvany** [comment] 2018-05-18 03:44
No reply in a month.  We can likely close this.  Feels like a dupe of the delegation lease #598

**Comment by orogvany** [comment] 2018-05-20 20:16
Closing in favor of #598

**Closed by orogvany** 2018-05-20 20:16 UTC
Labels: delegate, discussion
