### ISSUE TITLE
Time Synchronization on windows servers causing massive block losses. 

### ISSUE THREAD

**Issue by iiqqrs** [semuxproject/semux#685] opened 2018-03-03 04:35 UTC
Over the last 3 days of running a validator, I've been through three different servers first a personal desktop, next to a vps hosted at vultr recommended by a dev, and finally onto aws EC2.

All servers had sufficient resources 4+ cores 8+gb of ram, and 2+TB of monthly data. 

Last night before going to bed, I had set up my vultr server, waited for the first block to be mined so I knew it was working. I went to bed and woke up about 5 hours later and had already missed 3 blocks. Woke up and viewed this in the log:

2018-03-02T08:49:04-0500 INFO     SemuxBft         Entered propose: height = 111514, view = 1, primary = false, # connected validators = 1 + 40
2018-03-02T08:49:16-0500 INFO     SemuxBft         Entered validate: proposal = true, votes = [7, 0] [0, 0] [0, 0]
2018-03-02T08:49:16-0500 WARN     SemuxBft         **A block in the future is not allowed**
2018-03-02T08:49:22-0500 INFO     SemuxBft         Entered pre_commit: proposal = true, votes = [92, 1] [11, 0] [0, 0]

I'm really unaware why windows allows its atomic clock to fall out of sync as fast as it does but it has been a big issue on basically every windows instance I've ran in the last few days.

I know this is less a semux bug and more a windows bug however this is directly impacting validator performance and network stability on windows machines.

I'm not really sure what types of solutions are possible to ensure nodes always stay in sync, but I believe that as a peer-to-peer network there's a peer-to-peer solution. 

Address for bug bounty: 0x309a71649768d0fede969feb90c74d8338a8fdb3 would be nice to get back some of the now 25+ lost semux.

**Comment by cryptokat** [comment] 2018-03-03 04:47
Hello @iiqqrs 
I am closing this issue since the issue is not directly related to Semux wallet software.
See: https://serverfault.com/a/605551/112284

As an enhancement we may introduce a built-in NTP check: #426

**Closed by cryptokat** 2018-03-03 04:47 UTC
