### ISSUE TITLE
Block time: longer 30 seconds

### ISSUE THREAD

**Issue by telllic** [semuxproject/semux#622] opened 2018-01-31 14:43 UTC
Mainnet should theoretically produce 2,880 blocks per 24 hours. In reality, 2,880 blocks were produce in 25 - 26 hours. It is dispersion or bug?

Block time: 30 seconds. 2880 per 24 hours.

Below are the data from https://semux.info/ 

Block # 00100 -- 21:17:48, 20 Jan 2018 --
Block # 02980 -- 21:53:04, 21 Jan 2018 -- (+36 minuts)
Block # 05860 -- 22:24:51, 22 Jan 2018 -- (+31 minuts)
Block # 08740 -- 23:21:15, 23 Jan 2018 -- (+57 minuts)
Block # 11620 -- 00:43:50, 25 Jan 2018 -- (+1:22)
Block # 14500 -- 01:46:45, 26 Jan 2018 -- (+1:03)
Block # 17380 -- 03:02:00, 27 Jan 2018 -- (+1:16)
Block # 20260 -- 04:42:09, 28 Jan 2018 -- (+1:40)
Block # 23140 -- 06:47:52, 29 Jan 2018 -- (+2:05)
Block # 26020 -- 08:08:44, 30 Jan 2018 -- (+1:21)
Block # 28900 -- 09:46:59, 31 Jan 2018 -- (+1:38)

**Comment by AlexAltertrader** [comment] 2018-01-31 14:57
I think the problem is that in these long rounds, slow validators on weak channels slowed the rest of the validators.

**Comment by semuxdev** [comment] 2018-02-01 03:18
This is primarily resulted from validator missing their turns. Additional rounds are required for the block to be forged.

**Comment by orogvany** [comment] 2018-04-11 06:07
think this can be closed as answered.

**Closed** 2018-04-11 06:07 UTC
Labels: question
