### ISSUE TITLE
"Send" Tab - "From" section does not update. It is delayed

### ISSUE THREAD

**Issue by pibe182** [semuxproject/semux#678] opened 2018-02-28 11:39 UTC
"Send" Tab - "From" section does not update. It is delayed

#### System information

Semux version: v1.0.0-4a83a2d

OS & Version:  Windows 7 x86

When you do an action, like unvote or send SEM to another address, comes this problem.

#### Expected behaviour

"Send" tab - "From" section. It should display your available balance.

#### Actual behaviour

"Send" Tab - "From" section does not update. It is delayed.

#### Steps to reproduce the behaviour

Example:

1) I Unvote X SEM ("From section" should display X, it displays 0)

2) I close SEMUX client

3) I open SEMUX client, now "From section" is updated. I send X amount to another address.

4) "From section" should now show me 0, but it still shows me X.

5) I unvote some more votes, "From section" still shows me X.

6) I receive some SEM. "From section" still stuck in X. Whatever I do, it will still show me X until I close the client and open it again. Only then "From section" is updated correctly.

I think it is clear enough, but if it is not I will make a video for you.

![transferencia btc](https://user-images.githubusercontent.com/36785044/36785608-c921ca9a-1c59-11e8-8abb-3351bdd35e15.png)

**Comment by cryptokat** [comment] 2018-03-01 22:42
duplicate of #522

**Closed by cryptokat** 2018-03-01 22:42 UTC
