### ISSUE TITLE
Sending shows error message "Insufficient funds!" when trying to send entire account balance

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#593] opened 2018-01-26 22:07 UTC
#### System information

Semux version: `1.0.0`

OS & Version: `Ubuntu 16.04`

#### Expected behaviour

While sending a whole account amount users take the account balance shown on the UI and subtract the fee to calculate the account entire balance they want to send. Unfortunately the UI only shows up to 3 decimal points and rounds up the balance making it impossible for the user to figure out what the actual balance is in order to send it.

#### Actual behaviour
UI shows i.e. 100.125 SEM
User wants to send 100.12 and gets an error message "Insufficient funds! You need 100.125 SEM."
When looked up on the block explorer it shows full balance, i.e. 100.124989898 SEM.

#### Steps to reproduce the behaviour

1. Send .0001 from address A to address B
2. Try sending entire balance of A to B

**Comment by semuxdev** [comment] 2018-01-27 19:14
This may be related to #522. I assume the balance in the account drop list is not updated

**Comment by Messier81z** [comment] 2018-01-28 12:59
In this case the drop down shows "correct" value but it's rounded up and this is causing the problem.

As a separate issue I've experienced that the drop down value was not updated after I sent a transaction from that account. It took me a while to click around and it eventually picked up the new balance.

**Comment by cryptokat** [comment] 2018-02-22 20:06
Considered as a duplicate of #608

**Closed by cryptokat** 2018-02-22 20:06 UTC
Labels: GUI
